#
# Makefile for the Qualcomm Atheros network device drivers.
#

obj-$(CONFIG_SHORTCUT_FE) += sfe/shortcut-fe/
obj-$(CONFIG_SHORTCUT_FE) += sfe/fast-classifier/
obj-$(CONFIG_QCA7000) += qcaspi.o
obj-$(CONFIG_ESSEDMA) += essedma/
qcaspi-objs := qca_spi.o qca_framing.o qca_7k.o qca_debug.o
