# QCA IPQ4019 Sound Card Support
snd-soc-ipq4019-objs := ipq4019.o
snd-soc-ipq4019-cpu-dai-objs := ipq4019-cpu-dai.o
snd-soc-ipq4019-pcm-i2s-objs := ipq4019-pcm-i2s.o

obj-$(CONFIG_SND_QCA_SOC_IPQ4019) += snd-soc-ipq4019.o
obj-$(CONFIG_SND_IPQ4019_SOC_ADSS) += ipq4019-adss.o
obj-$(CONFIG_SND_IPQ4019_SOC_CPU_DAI) += snd-soc-ipq4019-cpu-dai.o
obj-$(CONFIG_SND_IPQ4019_SOC_STEREO) += ipq4019-stereo.o
obj-$(CONFIG_SND_IPQ4019_SOC_MBOX) += ipq4019-mbox.o
obj-$(CONFIG_SND_IPQ4019_SOC_PCM_I2S) += snd-soc-ipq4019-pcm-i2s.o
